package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;;

/**
 * Attachment generated by Justin Yang
 */
@Entity
@Table(name = "Attachment", catalog = "mydb")
public class Attachment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1418256796004491864L;
	private int id;
	private String name;
	private String url;
    private String attachmentType;
	private Document document;

	public Attachment() {
	}

	public Attachment(int id, Document document) {
		this.id = id;
		this.setDocument(document);
	}

	public Attachment(int id, String name, String url, Document document) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.setDocument(document);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

    @Column(name = "attachmentType", length = 50)
    public String getAttachmentType() {
        return attachmentType;
    }

    public void setAttachmentType(String attachmentType) {
        this.attachmentType = attachmentType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docId", nullable = false)
	public Document getDocument() {
		return document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

    public void updateBasicInfo(Attachment attachment) {
        if (attachment == null) {
            return;
        }

        String name = attachment.getName();
        if (name != null && !name.equals(this.name)) {
            this.name = name;
        }

        String url = attachment.getUrl();
        if (url != null && !url.equals(this.url)) {
            this.url = url;
        }

        String attachmentType = attachment.getAttachmentType();
        if (attachmentType != null && !attachmentType.equals(this.attachmentType)) {
            this.attachmentType = attachmentType;
        }
    }
}
