package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

/**
 * Attachment generated by Justin Yang
 */
public class Attachment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1418256796004491864L;
	private String id;
	private String name;
	private String url;
    private String attachmentType;
	private transient Document document;

	public Attachment() {
	}

	public Attachment(String id, Document document) {
		this.id = id;
		this.setDocument(document);
	}

	public Attachment(String id, String name, String url, Document document) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.setDocument(document);
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

    public String getAttachmentType() {
        return attachmentType;
    }

    public void setAttachmentType(String attachmentType) {
        this.attachmentType = attachmentType;
    }

	public Document getDocument() {
		return document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

    public void updateBasicInfo(Attachment attachment) {
        if (attachment == null) {
            return;
        }

        String name = attachment.getName();
        if (name != null && !name.equals(this.name)) {
            this.name = name;
        }

        String url = attachment.getUrl();
        if (url != null && !url.equals(this.url)) {
            this.url = url;
        }

        String attachmentType = attachment.getAttachmentType();
        if (attachmentType != null && !attachmentType.equals(this.attachmentType)) {
            this.attachmentType = attachmentType;
        }
    }
}
