package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentExtraProperty generated by Justin Yang
 */
public class DocumentExtraProperty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2370855789253507628L;
	private String id;
	private String propertyName;
	private transient DocumentType documentType;

	private transient Set<DocumentWithExtraProperty> extraProperties = new HashSet<DocumentWithExtraProperty>(
			0);

	public DocumentExtraProperty() {
	}

	public DocumentExtraProperty(String id, DocumentType documentType) {
		this.id = id;
		this.setDocumentType(documentType);
	}

	public DocumentExtraProperty(String id, String propertyName,
			DocumentType documentType) {
		this.id = id;
		this.propertyName = propertyName;
		this.setDocumentType(documentType);
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public DocumentType getDocumentType() {
		return documentType;
	}

	public void setDocumentType(DocumentType documentType) {
		this.documentType = documentType;
	}

	public Set<DocumentWithExtraProperty> getExtraProperties() {
		return extraProperties;
	}

	public void setExtraProperties(
			Set<DocumentWithExtraProperty> extraProperties) {
		this.extraProperties = extraProperties;
	}

}
