package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DocumentExtraProperty generated by Justin Yang
 */
@Entity
@Table(name = "DocumentExtraProperty", catalog = "mydb")
public class DocumentExtraProperty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2370855789253507628L;
	private int id;
	private String propertyName;
	private DocumentType documentType;
	
	private Set<DocumentWithExtraProperty> extraProperties = new HashSet<DocumentWithExtraProperty>(0);

	public DocumentExtraProperty() {
	}

	public DocumentExtraProperty(int id, DocumentType documentType) {
		this.id = id;
		this.setDocumentType(documentType);
	}

	public DocumentExtraProperty(int id, String propertyName, DocumentType documentType) {
		this.id = id;
		this.propertyName = propertyName;
		this.setDocumentType(documentType);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "propertyName", length = 45)
	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docTypeId", nullable = false)
	public DocumentType getDocumentType() {
		return documentType;
	}

	public void setDocumentType(DocumentType documentType) {
		this.documentType = documentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pk.documentExtraProperty")
	public Set<DocumentWithExtraProperty> getExtraProperties() {
		return extraProperties;
	}

	public void setExtraProperties(Set<DocumentWithExtraProperty> extraProperties) {
		this.extraProperties = extraProperties;
	}

}
