package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DocumentType generated by Justin Yang
 */
@Entity
@Table(name = "DocumentType", catalog = "mydb")
public class DocumentType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7939384004380348620L;
	private int id;
	private String name;
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<DocumentExtraProperty> extraProperties = new HashSet<DocumentExtraProperty>(
			0);

	public DocumentType() {
	}

	public DocumentType(int id) {
		this.id = id;
	}

	public DocumentType(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentType")
	public Set<Document> getDocuments() {
		return documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentType")
	public Set<DocumentExtraProperty> getExtraProperties() {
		return extraProperties;
	}

	public void setExtraProperties(Set<DocumentExtraProperty> extraProperties) {
		this.extraProperties = extraProperties;
	}

}
