package dmsystem.entity;

/**
 * Document generated by Justin Yang
 */
public class DocumentRelation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5895801624901036827L;
	private DocumentRelationId pk = new DocumentRelationId();

	public DocumentRelationId getPk() {
		return pk;
	}

	public void setPk(DocumentRelationId pk) {
		this.pk = pk;
	}
	
	public Document getReferer() {
		return getPk().getReferer();
	}
 
	public void setReferer(Document referer) {
		getPk().setReferer(referer);
	}
 
	public Document getReferee() {
		return getPk().getReferee();
	}
 
	public void setReferee(Document referee) {
		getPk().setReferee(referee);
	}
	
	public RelationType getRelationType() {
		return getPk().getRelationType();
	}
	
	public void setRelationType(RelationType relationType) {
		getPk().setRelationType(relationType);
	}
	
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
 
		DocumentRelation that = (DocumentRelation) o;
 
		if (getPk() != null ? !getPk().equals(that.getPk())
				: that.getPk() != null)
			return false;
 
		return true;
	}
 
	public int hashCode() {
		return (getPk() != null ? getPk().hashCode() : 0);
	}
}
