package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EvaluationExtraPropertyType generated by Justin Yang
 */
public class EvaluationExtraProperty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4893004450009980422L;
	private String id;
	private String propertyName;
	private Set<EvaluationWithExtraProperty> extraProperties = new HashSet<EvaluationWithExtraProperty>(0);

	public EvaluationExtraProperty() {
	}

	public EvaluationExtraProperty(String id) {
		this.id = id;
	}

	public EvaluationExtraProperty(String id, String propertyName) {
		this.id = id;
		this.propertyName = propertyName;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public Set<EvaluationWithExtraProperty> getExtraProperties() {
		return extraProperties;
	}

	public void setExtraProperties(Set<EvaluationWithExtraProperty> extraProperties) {
		this.extraProperties = extraProperties;
	}

}
