package dmsystem.entity;

/**
 * DocumentWithExtraProperty generated by Justin Yang
 */
public class EvaluationWithExtraProperty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1769070790656231325L;
	private EvaluationWithExtraPropertyId pk = new EvaluationWithExtraPropertyId();
	private String propertyValue;

	public EvaluationWithExtraProperty() {
	}

	public EvaluationWithExtraProperty(EvaluationWithExtraPropertyId pk) {
		this.pk = pk;
	}

	public EvaluationWithExtraPropertyId getPk() {
		return this.pk;
	}

	public void setPk(EvaluationWithExtraPropertyId pk) {
		this.pk = pk;
	}
	
	public Evaluation getEvaluation() {
		return getPk().getEvaluation();
	}
	
	public void setEvaluation(Evaluation evaluation) {
		getPk().setEvaluation(evaluation);;
	}
	
	public EvaluationExtraProperty getEvaluationExtraProperty() {
		return getPk().getEvaluationExtraProperty();
	}
	
	public void setEvaluationExtraProperty(EvaluationExtraProperty evaluationExtraProperty) {
		getPk().setEvaluationExtraProperty(evaluationExtraProperty);
	}

	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		EvaluationWithExtraProperty that = (EvaluationWithExtraProperty) o;

		if (getPk() != null ? !getPk().equals(that.getPk())
				: that.getPk() != null)
			return false;

		return true;
	}

	public int hashCode() {
		return (getPk() != null ? getPk().hashCode() : 0);
	}
}
