package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Operation generated by Justin Yang
 */
public class Operation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8075258073461994790L;
	private String id;
	private Integer type;
	private Date time;
	private String expression;
	private User user;

	public Operation() {
	}

	public Operation(String id, User user) {
		this.id = id;
		this.setUser(user);
	}

	public Operation(String id, Integer type, Date time, String expression,
			User user) {
		this.id = id;
		this.type = type;
		this.time = time;
		this.expression = expression;
		this.setUser(user);
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
