package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * RelationType generated by Justin Yang
 */
public class RelationType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7965059147597962153L;
	private String id;
	private String name;
	private transient Set<DocumentRelation> documentRelations = new HashSet<DocumentRelation>(0);

	public RelationType() {
	}

	public RelationType(String id) {
		this.id = id;
	}

	public RelationType(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<DocumentRelation> getDocumentRelations() {
		return documentRelations;
	}

	public void setDocumentRelations(Set<DocumentRelation> documentRelations) {
		this.documentRelations = documentRelations;
	}

}
