package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

/**
 * Tag generated by Justin Yang
 */

public class Tag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2139000863282894997L;
	private String id;
	private String name;
	private transient Document document = new Document();

	public Tag() {
	}

	public Tag(String id) {
		this.id = id;
	}

	public Tag(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Document getDocument() {
		return document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

}
