package dmsystem.entity;

// Generated Dec 16, 2013 7:25:34 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by Justin Yang
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8173965168787037049L;

    public static final String SESSION_KEY = "user_session_key";

	private String id;
	private String username;
	private String password;
	private String name;
	private Integer authority;
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<Evaluation> evaluations = new HashSet<Evaluation>(0);

	public User() {
	}

	public User(String id) {
		this.id = id;
	}

	public User(String id, String username, String password, String name,
			Integer authority) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.name = name;
		this.authority = authority;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAuthority() {
		return this.authority;
	}

	public void setAuthority(Integer authority) {
		this.authority = authority;
	}

	public Set<Document> getDocuments() {
		return documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	public Set<Evaluation> getEvaluations() {
		return evaluations;
	}

	public void setEvaluations(Set<Evaluation> evaluations) {
		this.evaluations = evaluations;
	}
}
